### ISSUE TITLE
How to enable exporting to Google Sheets

### ISSUE THREAD

**Issue by nwoodward** [terrywbrady/restReportTutorial#2]
First, thank you for the excellent tutorial. My question is about the Google Sheets App integration in demo6. I've created and deployed my Sheets App with the files from https://github.com/terrywbrady/PlainTextCSV_GoogleAppsScript. But I'm not sure where to insert the `this.gsheet = function(rows)...` Javascript. And it seems like there's another step to add the "Export to Google Sheets" button in index.html and/or query.html. Could you clarify the last steps I need to take?

**Comment by terrywbrady** [comment]
@nwoodward , it does look like I left a part of the integration out.  I no longer support a DSpace instance, so I do not have access to the repo where I had done this integration.  I will ask my former colleagues to see if they would share the html and js to enable this integration.

**Comment by nwoodward** [comment]
Thanks a lot. I appreciate it.

**Comment by terrywbrady** [comment]
@nwoodward , my Georgetown colleagues shared the code with me.  Let me know if this gets things working for you.

Here is the html definition of the Export to GSheets button.
```
          <button id="exportGsheet">Export to Google Sheets</button>
```

The following javascript passes each row of report data to the Google Sheets service.
```
        //GUCODE[twb27:gsheet requires a custom service]
        $("#exportGsheet").click(function(){
            self.gsheet($("#itemtable tr"));
        });
```

That calls the following
```
  this.gsheet = function(rows) {
    var form = $("<form/>");
    $("#itemdiv").append(form);
    form.hide();
    form.attr("method","POST");
    form.attr("action","https://script.google.com/a/macros/{custom_google_URL});
    var input = $("<textarea rows='10' cols='100'/>");
    input.attr("name","data");
    input.val(this.makeCsv(rows));
    form.append(input);
    input = $("<input type='submit'/>");
    form.append(input);
    form.submit();
  }
```
